🚨 compiler warnings erradicated, also build fixed
There were a lot of warnings reported for WASM 32b
architecture, because on it char* and uint8_t does
not match and therefore explicit cast statement is
needed. This commit also adds a fix for the header
which relates to 32 b architecture but that header
is always required by another libunistring header.

diff --git a/wasm/Dockerfile b/wasm/Dockerfile
--- a/wasm/Dockerfile
+++ b/wasm/Dockerfile
@@ -26,5 +26,8 @@ ADD pdcurses/wasm /opt/pdcurses/wasm
 WORKDIR /opt/pdcurses/wasm
 RUN emmake make
 
-# Misc
-RUN apt-get install -y libc6-dev-i386 || true
+# Misc.
+# Even though this package fails to install,
+# it leaves gnu/stubs-32.h in the include path.
+# (libunistring header files are trying to include this 32 bit header).
+RUN apt-get update && apt-get install -y libc6-dev-i386 || true
